### PR TITLE
better ED25519_SUPPORT conditional support

### PR DESCRIPTION
**Pull request by ghost**
1) making ED25519_SUPPORT turned off by default the way comments imply was intended

2) making some parts related to ED25519_SUPPORT compile conditionally

3) some refactoring to make wider array of compilers happy with types

### CODE REVIEW

**Comment by encedo** [comment]
Hi 

I will review all the proposals and merge with them.

Stay tuned.
Chris

**Comment by rusefillc** [comment]
@encedo any news on the merge?

**Comment by encedo** [comment]
Hi guys,
I'm happy to merge your changes but after the other merge conflicts show up. Could you please review it?
Chris

**Comment by rusefillc** [comment]
New version of PR https://github.com/encedo/hex2dfu/pull/9

**Comment by rusefillc** [comment]
@encedo please close this one

**Comment by encedo** [comment]
Nothing to do here, closing.

**Pull request closed without merging**
